# image: "rust:latest"

# services:
#  - postgres:latest

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - rustup update
    - cargo build

lint-test-job:
  stage: test
  script:
    - rustup update
    - rustup component add clippy
    - cargo clippy --fix

unit-test-job:
  stage: test
  script:
    - rustup update
    - cargo test

deploy-job:
  stage: deploy
  script:
    - rustup update
    - cargo build --release
